module Board where

message1 = "[\"coord\",[\"A\",\"6\"],\"result\",\"HIT\",\"prev\",null]"
message2 = "[\"coord\",[\"F\",\"6\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"D\",\"2\"],\"result\",null,\"prev\",null]]"
message3 = "[\"coord\",[],\"result\",\"HIT\",\"prev\",[\"coord\",[\"J\",\"3\"],\"result\",\"MISS\",\"prev\",null]]"

message4 = "[\"\",[\"J\",\"6\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"A\",\"7\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"J\",\"5\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"D\",\"1\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"E\",\"2\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"H\",\"10\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"D\",\"7\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"H\",\"6\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"H\",\"8\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"G\",\"4\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"E\",\"10\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"D\",\"6\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"C\",\"6\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"A\",\"10\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"A\",\"3\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"C\",\"2\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"C\",\"8\"],\"result\",\"HIT\",\"prev\",[\"coord\",[\"A\",\"2\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"G\",\"2\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"E\",\"4\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"A\",\"9\"],\"result\",\"HIT\",\"prev\",[\"coord\",[\"B\",\"5\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"D\",\"6\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"I\",\"8\"],\"result\",\"HIT\",\"prev\",[\"coord\",[\"B\",\"10\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"A\",\"9\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"J\",\"9\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"I\",\"3\"],\"result\",\"HIT\",\"prev\",[\"coord\",[\"G\",\"3\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"J\",\"7\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"D\",\"4\"],\"result\",null,\"prev\",null]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]"

message5 = "[\"coord\",[\"J\",\"6\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"A\",\"7\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"J\",\"5\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"D\",\"1\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"E\",\"2\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"H\",\"10\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"D\",\"7\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"H\",\"6\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"H\",\"8\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"G\",\"4\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"E\",\"10\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"D\",\"6\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"C\",\"6\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"A\",\"10\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"A\",\"3\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"C\",\"2\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"C\",\"8\"],\"result\",\"HIT\",\"prev\",[\"coord\",[\"A\",\"2\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"G\",\"2\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"E\",\"4\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"A\",\"9\"],\"result\",\"HIT\",\"prev\",[\"coord\",[\"B\",\"5\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"D\",\"6\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"I\",\"8\"],\"result\",\"HIT\",\"prev\",[\"coord\",[\"B\",\"10\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"A\",\"9\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"J\",\"9\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"I\",\"3\"],\"result\",\"HIT\",\"prev\",[\"coord\",[\"G\",\"3\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"J\",\"7\"],\"result\",\"MISS\",\"prev\",[\"coord\",[\"D\",\"4\"],\"result\",null,\"prev\",null]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]"
